config/routes.rb
Rails.application.routes.draw do
  resources :stores
  devise_for :users, controllers: {
    confirmations: 'users/confirmations'
  }
  ActiveAdmin.routes(self)
  get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  
  root to: "home#index"
  # root to: "products#index"
  resources :categories
  resources :brands
  resources :products

  resources :shopping_carts
  put '/shopping_carts/:id/confirm', to: 'shopping_carts#confirm', as: 'confirm_shopping_cart'
  put '/shopping_carts/:id/deliver', to: 'shopping_carts#deliver', as: 'deliver_shopping_cart'
  resources :orders

end

app/models/shopping_cart.rb
class ShoppingCart < ApplicationRecord
  belongs_to :user
  belongs_to :product
  belongs_to :order, optional: true

  validate :check_available

  def self.current_cart(user)
    ShoppingCart.where(order_id: nil, user_id: user)  
  end

  def self.submit_current_cart(user, order)
    carts = self.current_cart(user)    
    carts.update_all(order_id: order, status: "Pending")
    carts
  end

  def pinned?
    self.status == "Pending"
  end

  def order_confirmed?
    self.order.status == "Confirmed"
  end

  def confirmed?
    self.status == "Confirmed"
  end

  def self.seller_orders(user)
    # abort ShoppingCart.joins(:product).inspect 
    ShoppingCart.where.not(order_id: nil).where(product_id: user.products) 
  end

  before_save :calculate_price 
  after_update :check_status
  after_save :change_available_quantity_in_product 
  before_destroy :release_holding_quantity

  private
    def calculate_price
      # abort " #{product.price} self.price osama"
      self.price = product.price * self.quantity
      # abort " #{self.price} self.price osama"
    end

    def check_status
      # abort (order.present?).inspect
      # abort order.update_status(self.status)
      if order.present?
        order.update_status(self.status)
      end
    end

    def available_quantity?
      available = product.in_stock_quantity
      quantity <= available
    end

    def check_available
      unless available_quantity?
        errors.add(:quantity, "sorry quantity no available ")
      end  
    end

    def release_holding_quantity
      product.change_available_quantity -(self.quantity)
    end

    def change_available_quantity_in_product
      new_number = self.quantity
      old_number = self.quantity_before_last_save
      unless old_number.nil?
        new_number -= old_number
      end
      product.change_available_quantity new_number
    end
end

app/controllers/shopping_carts_controller.rb
class ShoppingCartsController < ApplicationController
  respond_to :html, :js
  before_action :set_shopping_cart, only: [:show, :edit, :update, :destroy]

  # GET /shopping_carts
  # GET /shopping_carts.json
  def index
    if(current_user.buyer?)
      @shopping_carts = ShoppingCart.current_cart(current_user.id)
    elsif(current_user.seller?)
      @shopping_carts = ShoppingCart.seller_orders(current_user)
    end
  end

  # GET /shopping_carts/1
  # GET /shopping_carts/1.json
  def show
    redirect_to shopping_carts_path
  end

  # GET /shopping_carts/new
  def new
    @shopping_cart = ShoppingCart.new
    authorize! :create, @shopping_cart
  end

  # GET /shopping_carts/1/edit
  def edit
  end

  # POST /shopping_carts
  # POST /shopping_carts.json
  def create
    # abort shopping_cart_params.inspect
    @shopping_cart = ShoppingCart.new(shopping_cart_params.merge(user_id: current_user.id, order_id: nil))
    # abort @shopping_cart.inspect

    respond_to do |format|
      if @shopping_cart.save
        # abort @shopping_cart.inspect
        format.html { redirect_to @shopping_cart, notice: 'Shopping cart was successfully created.' }
        format.json { render  @shopping_cart, status: :created, location: @shopping_cart }
      else
        # abort @shopping_cart.inspect
        format.html { render :new }
        format.json { render json: @shopping_cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shopping_carts/1
  # PATCH/PUT /shopping_carts/1.json
  def update
    # abort shopping_cart_params_update.inspect
    authorize! :update, @shopping_cart
    respond_to do |format|
      if @shopping_cart.update(shopping_cart_params_update)
        format.html { redirect_to @shopping_cart, notice: 'Shopping cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @shopping_cart }
      else
        format.html { render :edit }
        format.json { render json: @shopping_cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shopping_carts/1
  # DELETE /shopping_carts/1.json
  def destroy
    @shopping_cart.destroy
    respond_to do |format|
      format.html { redirect_to shopping_carts_url, notice: 'Shopping cart was successfully destroyed.' }
      format.js
      format.json { head :no_content }
    end
  end
  
  def confirm
    @shopping_cart = ShoppingCart.find(params[:id])
    authorize! :update, @shopping_cart
    ShoppingCart.find(params[:id]).update(status: "Confirmed")
    redirect_to shopping_carts_path 
  end

  def delever
    @shopping_cart = ShoppingCart.find(params[:id])
    authorize! :update, @shopping_cart
    if (@shopping_cart.order.status == "Confirmed")
      @shopping_cart.update(status: "Delevered")
    end
    redirect_to shopping_carts_path 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shopping_cart
      @shopping_cart = ShoppingCart.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def shopping_cart_params
      
      params.permit(:product_id, :quantity)
    end

    def shopping_cart_params_update   
      params.require(:shopping_cart).permit(:quantity)
    end
end

app/helpers/shopping_carts_helper.rb
module ShoppingCartsHelper
end

app/views/shopping_carts/_form.html.erb
<%= form_with(model: shopping_cart, local: true) do |form| %>
  <% if shopping_cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shopping_cart.errors.count, "error") %> prohibited this shopping_cart from being saved:</h2>

      <ul>
        <% shopping_cart.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%if @shopping_cart.new_record? %>
    <div class="field">
      <%= form.label :product_id %>
      <%= form.text_field :product_id %>
    </div>
  <%end%>
  <div class="field">
    <%= form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/shopping_carts/create.js.erb
console.log("done create")

app/views/shopping_carts/destroy.js.erb
console.log("deleted")
$("form.button_to").on('ajax:success', function(event, data, status, xhr) {
  console.log(event)
});

app/views/shopping_carts/edit.html.erb
<h1>Editing Shopping Cart</h1>

<%= render 'form', shopping_cart: @shopping_cart %>

<%= link_to 'Show', @shopping_cart %> |
<%= link_to 'Back', shopping_carts_path %>

app/views/shopping_carts/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Shopping Carts</h1>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">User</th>
      <th scope="col">Product</th>
      <th scope="col">Quantity</th>
      <th scope="col">Price</th>
      <th scope="col">Order</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shopping_carts.each do |shopping_cart| %>
      <tr>
        <td><%= shopping_cart.user_id %></td>
        <td><%= shopping_cart.product.title %></td>
        <td>
          <%= form_with(url: shopping_cart, method: "put") do |form| %>
            <%= form.number_field :quantity, value: shopping_cart.quantity %>
            <%= form.hidden_field(:product_id, :value => shopping_cart.product.id) %>
            <%= form.submit "add" %>
          <% end %>
        </td>
        <td><%= shopping_cart.price %></td>
        <td><%= shopping_cart.order_id %></td>
        <td><%= link_to 'Show', shopping_cart %></td>
        <%if current_user.buyer? %>
          <td><%= link_to 'Edit', edit_shopping_cart_path(shopping_cart) %></td>
        <%elsif shopping_cart.pinned? %>
          <td><%= link_to 'Confirm', confirm_shopping_cart_path(shopping_cart), method: :put %></td>
        <%elsif shopping_cart.confirmed? && shopping_cart.order_confirmed? %>
          <td><%= link_to 'deliver', deliver_shopping_cart_path(shopping_cart), method: :put  %></td>
        <%else%>
          <td>confirming...</td>
        <%end%>
        
        <td><%= link_to 'Destroy', shopping_cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%if @shopping_carts.count > 0 %>
  <div class="d-flex justify-content-end">
    <%= link_to "Checkout", orders_path, method: :post, class: "btn btn-primary" %>
  </div>
<%end%>

<br>

<%= link_to 'New Shopping Cart', new_shopping_cart_path %>

app/views/shopping_carts/new.html.erb
<h1>New Shopping Cart</h1>

<%= render 'form', shopping_cart: @shopping_cart %>

<%= link_to 'Back', shopping_carts_path %>

app/views/shopping_carts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @shopping_cart.user_id %>
</p>

<p>
  <strong>Product:</strong>
  <%= @shopping_cart.product_id %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @shopping_cart.quantity %>
</p>

<p>
  <strong>Price:</strong>
  <%= @shopping_cart.price %>
</p>

<p>
  <strong>Order:</strong>
  <%= @shopping_cart.order_id %>
</p>

<%= link_to 'Edit', edit_shopping_cart_path(@shopping_cart) %> |
<%= link_to 'Back', shopping_carts_path %>