config/routes.rb
Rails.application.routes.draw do
  resources :stores
  devise_for :users, controllers: {
    confirmations: 'users/confirmations'
  }
  ActiveAdmin.routes(self)
  get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  
  root to: "home#index"
  # root to: "products#index"
  resources :categories
  resources :brands
  resources :products

  resources :shopping_carts
  put '/shopping_carts/:id/confirm', to: 'shopping_carts#confirm', as: 'confirm_shopping_cart'
  put '/shopping_carts/:id/deliver', to: 'shopping_carts#deliver', as: 'deliver_shopping_cart'
  resources :orders

end

app/models/store.rb
class Store < ApplicationRecord
  belongs_to :user
  has_many :products
    delegate :can?, :cannot?, to: :ability
    def ability
      @ability ||= Ability.new(self)
    end

end

app/controllers/stores_controller.rb
class StoresController < InheritedResources::Base
  load_and_authorize_resource
  
  private

    def store_params
      params.require(:store).permit(:name, :description, :user_id)
    end

end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<%= form_with(model: store, local: true) do |form| %>
  <% if store.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(store.errors.count, "error") %> prohibited this store from being saved:</h2>

      <ul>
        <% store.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stores/edit.html.erb
<h1>Editing Store</h1>

<%= render 'form', store: @store %>

<%= link_to 'Show', @store %> |
<%= link_to 'Back', stores_path %>

app/views/stores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Stores</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stores.each do |store| %>
    <% if can? :read, store %>
      <tr>
        <td><%= store.name %></td>
        <td><%= store.description %></td>
        <td><%= store.user_id %></td>
        <td><%= link_to 'Show', store %></td>
        <td><%= link_to 'Edit', edit_store_path(store) %></td>
        <% if can? :destroy, store %>
          <td><%= link_to 'Destroy', store, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end  %>
    <% end %>
  </tbody>
</table>

<br>

<% if can? :create, Store %>
  <%= link_to 'New Store', new_store_path %>
<% end %>

app/views/stores/new.html.erb
<h1>New Store</h1>

<%= render 'form', store: @store %>

<%= link_to 'Back', stores_path %>

app/views/stores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @store.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @store.description %>
</p>

<p>
  <strong>User:</strong>
  <%= @store.user_id %>
</p>

<%= link_to 'Edit', edit_store_path(@store) %> |
<%= link_to 'Back', stores_path %>