config/routes.rb
Rails.application.routes.draw do
  resources :stores
  devise_for :users, controllers: {
    confirmations: 'users/confirmations'
  }
  ActiveAdmin.routes(self)
  get 'home/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  
  root to: "home#index"
  # root to: "products#index"
  resources :categories
  resources :brands
  resources :products

  resources :shopping_carts
  put '/shopping_carts/:id/confirm', to: 'shopping_carts#confirm', as: 'confirm_shopping_cart'
  put '/shopping_carts/:id/deliver', to: 'shopping_carts#deliver', as: 'deliver_shopping_cart'
  resources :orders

end

app/views/layouts/_alerts.html.erb
<p class="notice <%= "success_msg" if notice  %> text-center"><%= notice %></p>
<p class="alert  <%= "error_msg" if alert  %> text-center"><%= alert %></p>

app/views/layouts/_header.html.erb
    <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <%= link_to "logo", root_path, :class=>"navbar-brand" %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <%= link_to "Home", root_path, :class=>"nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Brands", brands_path, :class=>"nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Categories", categories_path, :class=>"nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Products", products_path, :class=>"nav-link" %>
          </li>
          <% if user_signed_in? %>
            <li class="nav-item active">
              <%= link_to "#{current_user.buyer? ? 'Shopping Cart' : 'Orders'}", shopping_carts_path, :class=>"nav-link" %>
            </li>
          <% end %>
          
        </ul>
        <ul class="navbar-nav ml-auto">
          <% if !user_signed_in? %>
            <li class="nav-item">
              <%= link_to "Login", new_user_session_path, :class=>"nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "SignUp", new_user_registration_path, :class=>"nav-link" %>
            </li>
          <% else %>
            <% if current_user.avatar.attached? %>
              <li class="nav-item">
                <span class="nav-link"><%= image_tag url_for(current_user.avatar), width:40, height:30 %></span>
              </li>
            <% end %>
            <li class="nav-item">
              <span class="nav-link"><%= current_user.username %></span>
            </li>
            <li class="nav-item">
              <%= link_to "View Cart", shopping_carts_path, :class => "nav-link" %>
            </li>
            <% if current_user.admin? || current_user.seller? %>
              <li class="nav-item">
              <%= link_to "Manage", admin_root_path, :class=>"nav-link" %>
              </li>
            <% end %>
            <li class="nav-item">
              <%= link_to 'Edit', edit_user_registration_path, :class=>"nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to 'Logout', destroy_user_session_path, method: :delete, :class=>"nav-link" %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>
  </header>
<% if current_page?(root_path) %>
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class=""></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1" class=""></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2" class="active"></li>
      </ol>
      <div class="carousel-inner" role="listbox">
        <div class="carousel-item">
          <%= image_tag "bg1.jpg", class: "d-block img-fluid w-100", alt: "First slide" %>
        </div>
        <div class="carousel-item">
          <%= image_tag "bg2.jpg", class: "d-block img-fluid w-100", alt: "Second slide" %>
        </div>
        <div class="carousel-item active">
          <%= image_tag "bg3.jpg", class: "d-block img-fluid w-100", alt: "Third slide" %>
        </div>
      </div>
      <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ITIEcommerceRailsProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => "reload" %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <%= render "layouts/alerts" %>
      <%= yield %>
    </div>
  </body>
</html>